apiVersion: pkg.crossplane.io/v1beta1
kind: Function
metadata:
  name: function-patch-and-transform
spec:
  package: xpkg.crossplane.io/crossplane-contrib/function-patch-and-transform:v0.8.2

---
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: aws-postgresql
  labels:
    provider: aws
    db: postgresql
spec:
  compositeTypeRef:
    apiVersion: devopstoolkitseries.com/v1alpha1
    kind: SQL
  pipeline:
    - step: patch-and-transform
      functionRef:
        name: function-patch-and-transform
      input:
        apiVersion: pt.fn.crossplane.io/v1beta1
        kind: Resources   
        resources:
        - name: vpc
          base:
            apiVersion: ec2.aws.upbound.io/v1beta1
            kind: VPC
            spec:
              forProvider:
                region: us-east-1
                cidrBlock: 11.0.0.0/16
                enableDnsSupport: true
                enableDnsHostnames: true
        - name: subnet-a
          base:
            apiVersion: ec2.aws.upbound.io/v1beta1
            kind: Subnet
            metadata:
              labels:
                zone: us-east-1a
            spec:
              forProvider:
                region: us-east-1
                availabilityZone: us-east-1a
                cidrBlock: 11.0.0.0/24
                vpcIdSelector:
                  matchLabels:
                    crossplane.io/composite: silly-demo-db-9w8xd
        - name: subnet-b
          base:
            apiVersion: ec2.aws.upbound.io/v1beta1
            kind: Subnet
            metadata:
              labels:
                zone: us-east-1b
            spec:
              forProvider:
                region: us-east-1
                availabilityZone: us-east-1b
                cidrBlock: 11.0.1.0/24
                vpcIdSelector:
                  matchLabels:
                    crossplane.io/composite: silly-demo-db-9w8xd
        - name: subnet-c
          base:
            apiVersion: ec2.aws.upbound.io/v1beta1
            kind: Subnet
            metadata:
              labels:
                zone: us-east-1c
            spec:
              forProvider:
                region: us-east-1
                availabilityZone: us-east-1c
                cidrBlock: 11.0.2.0/24
                vpcIdSelector:
                  matchLabels:
                    crossplane.io/composite: silly-demo-db-9w8xd
        - name: subnetgroup
          base:
            apiVersion: rds.aws.upbound.io/v1beta1
            kind: SubnetGroup
            spec:
              forProvider:
                region: us-east-1
                description: I'm too lazy to write a good description
                subnetIdSelector:
                  matchLabels:
                    crossplane.io/composite: silly-demo-db-9w8xd
        - name: gateway
          base:
            apiVersion: ec2.aws.upbound.io/v1beta1
            kind: InternetGateway
            spec:
              forProvider:
                region: us-east-1
                vpcIdSelector:
                  matchLabels:
                    crossplane.io/composite: silly-demo-db-9w8xd
        - name: routeTable
          base:
            apiVersion: ec2.aws.upbound.io/v1beta1
            kind: RouteTable
            spec:
              forProvider:
                region: us-east-1
                vpcIdSelector:
                  matchLabels:
                    crossplane.io/composite: silly-demo-db-9w8xd
        - name: route
          base:
            apiVersion: ec2.aws.upbound.io/v1beta1
            kind: Route
            spec:
              forProvider:
                region: us-east-1
                routeTableIdSelector:
                  matchLabels:
                    crossplane.io/composite: silly-demo-db-9w8xd
                destinationCidrBlock: 0.0.0.0/0
                gatewayIdSelector:
                  matchLabels:
                    crossplane.io/composite: silly-demo-db-9w8xd
        - name: mainRouteTableAssociation
          base:
            apiVersion: ec2.aws.upbound.io/v1beta1
            kind: MainRouteTableAssociation
            spec:
              forProvider:
                region: us-east-1
                routeTableIdSelector:
                  matchLabels:
                    crossplane.io/composite: silly-demo-db-9w8xd
                vpcIdSelector:
                  matchLabels:
                    crossplane.io/composite: silly-demo-db-9w8xd
        - name: routeTableAssociation1a
          base:
            apiVersion: ec2.aws.upbound.io/v1beta1
            kind: RouteTableAssociation
            spec:
              forProvider:
                region: us-east-1
                routeTableIdSelector:
                  matchLabels:
                    crossplane.io/composite: silly-demo-db-9w8xd
                subnetIdSelector:
                  matchLabels:
                    crossplane.io/composite: silly-demo-db-9w8xd
        - name: routeTableAssociation1b
          base:
            apiVersion: ec2.aws.upbound.io/v1beta1
            kind: RouteTableAssociation
            spec:
              forProvider:
                region: us-east-1
                routeTableIdSelector:
                  matchLabels:
                    crossplane.io/composite: silly-demo-db-9w8xd
                subnetIdSelector:
                  matchLabels:
                    crossplane.io/composite: silly-demo-db-9w8xd
        - name: routeTableAssociation1c
          base:
            apiVersion: ec2.aws.upbound.io/v1beta1
            kind: RouteTableAssociation
            spec:
              forProvider:
                region: us-east-1
                routeTableIdSelector:
                  matchLabels:
                    crossplane.io/composite: silly-demo-db-9w8xd
                subnetIdSelector:
                  matchLabels:
                    crossplane.io/composite: silly-demo-db-9w8xd
        - name: securityGroup
          base:
            apiVersion: ec2.aws.upbound.io/v1beta1
            kind: SecurityGroup
            spec:
              forProvider:
                description: I am too lazy to write descriptions
                region: us-east-1
                vpcIdSelector:
                  matchLabels:
                    crossplane.io/composite: silly-demo-db-9w8xd
        - name: securityGroupRule
          base:
            apiVersion: ec2.aws.upbound.io/v1beta1
            kind: SecurityGroupRule
            spec:
              forProvider:
                description: I am too lazy to write descriptions
                region: us-east-1
                type: ingress
                fromPort: 5432
                toPort: 5432
                protocol: tcp
                cidrBlocks:
                  - 0.0.0.0/0
                securityGroupIdSelector:
                  matchLabels:
                    crossplane.io/composite: silly-demo-db-9w8xd
        - name: rdsinstance
          base:
            apiVersion: rds.aws.upbound.io/v1beta1
            kind: Instance
            spec:
              forProvider:
                region: us-east-1
                dbSubnetGroupNameSelector:
                  matchLabels:
                    crossplane.io/composite: silly-demo-db-9w8xd
                vpcSecurityGroupIdSelector:
                  matchLabels:
                    crossplane.io/composite: silly-demo-db-9w8xd
                instanceClass: db.t4g.micro
                username: masteruser
                engine: postgres
                engineVersion: "17.5"
                skipFinalSnapshot: true
                publiclyAccessible: true
                allocatedStorage: 50
                passwordSecretRef:
                  namespace: a-team
                  key: password
                  name: silly-demo-db-password
---                  
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  labels:
    location: remote
    type: backend-db-aws
  name: app-backend-db-aws
spec:
  compositeTypeRef:
    apiVersion: devopstoolkitseries.com/v1alpha1
    kind: App
  patchSets:
  - name: metadata
    patches:
    - fromFieldPath: metadata.labels
  resources:
  - base:
      apiVersion: kubernetes.crossplane.io/v1alpha1
      kind: ProviderConfig
      spec:
        credentials:
          source: InjectedIdentity
    name: kubernetes
    patches:
    - fromFieldPath: spec.id
      toFieldPath: metadata.name
    readinessChecks:
    - type: None
  - base:
      apiVersion: kubernetes.crossplane.io/v1alpha1
      kind: Object
      spec:
        forProvider:
          manifest:
            apiVersion: apps/v1
            kind: Deployment
            spec:
              template:
                spec:
                  containers:
                  - env:
                    - name: DB_ENDPOINT
                      valueFrom:
                        secretKeyRef:
                          key: endpoint
                    - name: DB_PASSWORD
                      valueFrom:
                        secretKeyRef:
                          key: password
                    - name: DB_PORT
                      valueFrom:
                        secretKeyRef:
                          key: port
                          optional: true
                    - name: DB_USERNAME
                      valueFrom:
                        secretKeyRef:
                          key: username
                    - name: DB_NAME
                    livenessProbe:
                      httpGet:
                        path: /
                        port: 80
                    name: backend
                    ports:
                    - containerPort: 80
                    readinessProbe:
                      httpGet:
                        path: /
                        port: 80
                    resources:
                      limits:
                        cpu: 250m
                        memory: 256Mi
                      requests:
                        cpu: 125m
                        memory: 128Mi
    name: deployment
    patches:
    - fromFieldPath: spec.id
      toFieldPath: metadata.name
      transforms:
      - string:
          fmt: '%s-deployment'
        type: string
    - fromFieldPath: spec.id
      toFieldPath: spec.forProvider.manifest.metadata.name
    - fromFieldPath: spec.parameters.namespace
      toFieldPath: spec.forProvider.manifest.metadata.namespace
    - fromFieldPath: spec.id
      toFieldPath: spec.forProvider.manifest.metadata.labels.app
    - fromFieldPath: spec.id
      toFieldPath: spec.forProvider.manifest.spec.selector.matchLabels.app
    - fromFieldPath: spec.id
      toFieldPath: spec.forProvider.manifest.spec.template.metadata.labels.app
    - fromFieldPath: spec.parameters.image
      toFieldPath: spec.forProvider.manifest.spec.template.spec.containers[0].image
    - fromFieldPath: spec.parameters.port
      toFieldPath: spec.forProvider.manifest.spec.template.spec.containers[0].ports[0].containerPort
    - fromFieldPath: spec.parameters.port
      toFieldPath: spec.forProvider.manifest.spec.template.spec.containers[0].livenessProbe.httpGet.port
    - fromFieldPath: spec.parameters.port
      toFieldPath: spec.forProvider.manifest.spec.template.spec.containers[0].readinessProbe.httpGet.port
    - fromFieldPath: spec.id
      toFieldPath: spec.forProvider.manifest.spec.template.spec.containers[0].env[0].valueFrom.secretKeyRef.name
    - fromFieldPath: spec.id
      toFieldPath: spec.forProvider.manifest.spec.template.spec.containers[0].env[1].valueFrom.secretKeyRef.name
    - fromFieldPath: spec.id
      toFieldPath: spec.forProvider.manifest.spec.template.spec.containers[0].env[2].valueFrom.secretKeyRef.name
    - fromFieldPath: spec.id
      toFieldPath: spec.forProvider.manifest.spec.template.spec.containers[0].env[3].valueFrom.secretKeyRef.name
    - fromFieldPath: spec.id
      toFieldPath: spec.forProvider.manifest.spec.template.spec.containers[0].env[4].value
    - fromFieldPath: spec.id
      toFieldPath: spec.providerConfigRef.name
    readinessChecks:
    - type: None
  - base:
      apiVersion: kubernetes.crossplane.io/v1alpha1
      kind: Object
      spec:
        forProvider:
          manifest:
            apiVersion: v1
            kind: Service
            spec:
              ports:
              - name: http
                port: 80
                protocol: TCP
                targetPort: 80
              type: ClusterIP
    name: service
    patches:
    - fromFieldPath: spec.id
      toFieldPath: metadata.name
      transforms:
      - string:
          fmt: '%s-service'
        type: string
    - fromFieldPath: spec.id
      toFieldPath: spec.forProvider.manifest.metadata.name
    - fromFieldPath: spec.parameters.namespace
      toFieldPath: spec.forProvider.manifest.metadata.namespace
    - fromFieldPath: spec.id
      toFieldPath: spec.forProvider.manifest.metadata.labels.app
    - fromFieldPath: spec.id
      toFieldPath: spec.forProvider.manifest.spec.selector.app
    - fromFieldPath: spec.parameters.port
      toFieldPath: spec.forProvider.manifest.spec.ports[0].port
    - fromFieldPath: spec.parameters.port
      toFieldPath: spec.forProvider.manifest.spec.ports[0].targetPort
    - fromFieldPath: spec.id
      toFieldPath: spec.providerConfigRef.name
    readinessChecks:
    - type: None
  - base:
      apiVersion: kubernetes.crossplane.io/v1alpha1
      kind: Object
      spec:
        forProvider:
          manifest:
            apiVersion: networking.k8s.io/v1
            kind: Ingress
            metadata:
              annotations:
                ingress.kubernetes.io/ssl-redirect: "false"
            spec:
              rules:
              - host: devopstoolkitseries.com
                http:
                  paths:
                  - backend:
                      service:
                        name: devops-toolkit
                        port:
                          number: 80
                    path: /
                    pathType: ImplementationSpecific
    name: ingress
    patches:
    - fromFieldPath: spec.id
      toFieldPath: metadata.name
      transforms:
      - string:
          fmt: '%s-ingress'
        type: string
    - fromFieldPath: spec.id
      toFieldPath: spec.forProvider.manifest.metadata.name
    - fromFieldPath: spec.parameters.namespace
      toFieldPath: spec.forProvider.manifest.metadata.namespace
    - fromFieldPath: spec.id
      toFieldPath: spec.forProvider.manifest.metadata.labels.app
    - fromFieldPath: spec.parameters.host
      toFieldPath: spec.forProvider.manifest.spec.rules[0].host
    - fromFieldPath: spec.id
      toFieldPath: spec.forProvider.manifest.spec.rules[0].http.paths[0].backend.service.name
    - fromFieldPath: spec.parameters.port
      toFieldPath: spec.forProvider.manifest.spec.rules[0].http.paths[0].backend.service.port.number
    - fromFieldPath: spec.id
      toFieldPath: spec.providerConfigRef.name
    - fromFieldPath: spec.forProvider.manifest.spec.rules[0].host
      toFieldPath: status.host
      type: ToCompositeFieldPath
    readinessChecks:
    - type: None
  - base:
      apiVersion: kubernetes.crossplane.io/v1alpha1
      kind: Object
      spec:
        forProvider:
          manifest:
            apiVersion: devopstoolkitseries.com/v1alpha1
            kind: SQLClaim
            spec:
              compositionSelector:
                matchLabels:
                  db: postgresql
                  provider: aws-official
    name: sql
    patches:
    - fromFieldPath: spec.id
      toFieldPath: metadata.name
      transforms:
      - string:
          fmt: '%s-sql'
        type: string
    - fromFieldPath: spec.id
      toFieldPath: spec.forProvider.manifest.metadata.labels.app
    - fromFieldPath: spec.id
      toFieldPath: spec.forProvider.manifest.spec.id
    - fromFieldPath: spec.parameters.dbVersion
      toFieldPath: spec.forProvider.manifest.spec.parameters.version
    - fromFieldPath: spec.parameters.db.version
      toFieldPath: spec.forProvider.manifest.spec.parameters.version
    - fromFieldPath: spec.parameters.db.type
      toFieldPath: spec.forProvider.manifest.spec.parameters.version
    - fromFieldPath: spec.id
      toFieldPath: spec.providerConfigRef.name
    - fromFieldPath: spec.parameters.namespace
      toFieldPath: spec.forProvider.manifest.metadata.namespace
  - base:
      apiVersion: kubernetes.crossplane.io/v1alpha1
      kind: Object
      spec:
        forProvider:
          manifest:
            apiVersion: external-secrets.io/v1beta1
            kind: ExternalSecret
            spec:
              dataFrom:
              - extract:
                  key: production-postgresql
              refreshInterval: 5m
              secretStoreRef:
                kind: ClusterSecretStore
                name: aws
              target:
                creationPolicy: Owner
    name: sql-secret
    patches:
    - fromFieldPath: spec.id
      toFieldPath: metadata.name
      transforms:
      - string:
          fmt: '%s-password'
        type: string
    - fromFieldPath: spec.id
      toFieldPath: spec.forProvider.manifest.spec.target.name
      transforms:
      - string:
          fmt: '%s-password'
        type: string
    - fromFieldPath: spec.id
      toFieldPath: spec.forProvider.manifest.metadata.name
    - fromFieldPath: spec.parameters.namespace
      toFieldPath: spec.forProvider.manifest.metadata.namespace
    - fromFieldPath: spec.id
      toFieldPath: spec.forProvider.manifest.metadata.labels.app
    - fromFieldPath: spec.id
      toFieldPath: spec.providerConfigRef.name
---